---
name: Lint

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: MegaLinter
        uses: oxsecurity/megalinter/flavors/documentation@v7
        env:
          PRINT_ALPACA: false
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'workflow_dispatch' }}
          ENABLE_LINTERS: |-
            ${{
              join(
                fromJSON('
                  [
                    "ACTION_ACTIONLINT",
                    "BASH_SHELLCHECK",
                    "COPYPASTE_JSCPD",
                    "DOCKERFILE_HADOLINT",
                    "MARKDOWN_MARKDOWNLINT",
                    "REPOSITORY_GIT_DIFF",
                    "REPOSITORY_SECRETLINT",
                    "YAML_PRETTIER",
                    "YAML_YAMLLINT"
                  ]
                '),
                ','
              )
            }}
          MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .github/linters/markdownlint.config.yaml
          MARKDOWN_MARKDOWNLINT_RULES_PATH: .github/
          YAML_YAMLLINT_CONFIG_FILE: .github/linters/.yamllint.yaml
          YAML_PRETTIER_CONFIG_FILE: .github/linters/.prettierrc.yaml
