---
name: Lint

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: MegaLinter
        uses: megalinter/megalinter@v5
        env:
          PRINT_ALPACA: false
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'workflow_dispatch' }}
          ENABLE_LINTERS: |-
            ${{
              join(
                fromJSON('
                  [
                    "ACTION_ACTIONLINT",
                    "COPYPASTE_JSCPD",
                    "CREDENTIALS_SECRETLINT",
                    "DOCKERFILE_HADOLINT",
                    "GIT_GIT_DIFF",
                    "MARKDOWN_MARKDOWNLINT",
                    "TERRAFORM_TERRAFORM_FMT",
                    "YAML_PRETTIER",
                    "YAML_YAMLLINT"
                  ]
                '),
                ','
              )
            }}
          MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .github/linters/markdownlint.config.yaml
          MARKDOWN_MARKDOWNLINT_RULES_PATH: .github/
          PYTHON_FLAKE8_CONFIG_FILE: .github/linters/.flake8
          YAML_YAMLLINT_CONFIG_FILE: .github/linters/.yamllint.yaml
          YAML_PRETTIER_FILTER_REGEX_EXCLUDE: "(.*\\.sops\\.ya?ml)"
